name: Deploy CareConnect-Final

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # ✅ since index.html is directly inside CareConnect/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
